EXTRA_LISTINGS = [
    # --- LADAKH & NORTH INDIA ---
    {
        "host_type": 1,
        "title": "Leh Luxury Mountain Retreat",
        "description": "Traditional Ladakhi mud-brick architecture meets modern premium comfort. Enjoy wood-burning stoves, panoramic views of the Stok Range, and local organic meals.",
        "category": "Countryside",
        "price_per_night": 140.00,
        "cleaning_fee": 30.00,
        "service_fee": 15.00,
        "address": "Stok Palace Road",
        "city": "Leh",
        "country": "India",
        "latitude": 34.0722,
        "longitude": 77.5381,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Scenic Glamping Dome near Pangong Lake",
        "description": "Geodesic dome perched 14,000 feet above sea level. Wake up to direct views of the deep-blue Pangong Lake. Star-gazing telescope and indoor fireplace included.",
        "category": "Desert",
        "price_per_night": 180.00,
        "cleaning_fee": 40.00,
        "service_fee": 20.00,
        "address": "Spangmik Village",
        "city": "Pangong Tso",
        "country": "India",
        "latitude": 33.9015,
        "longitude": 78.4612,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["Heating", "Free parking", "Workspace"]
    },
    {
        "host_type": 1,
        "title": "Rustic Stone Cabin in Nubra Valley",
        "description": "Cozy stone cabin surrounded by apricot orchards. Relax on the rooftop patio overlooking the cold sand dunes and Karakoram ranges.",
        "category": "Cabins",
        "price_per_night": 95.00,
        "cleaning_fee": 20.00,
        "service_fee": 10.00,
        "address": "Hunder Village Dunes",
        "city": "Nubra Valley",
        "country": "India",
        "latitude": 34.5878,
        "longitude": 77.4261,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "Free parking"]
    },

    # --- INDIAN TEMPLES & HERITAGE ---
    {
        "host_type": 2,
        "title": "Spiritual Heritage Home near Kashi Vishwanath",
        "description": "A beautifully restored 200-year-old mansion steps away from the Ganges and Kashi Vishwanath Temple. Rooftop views of morning Ganga Aarti.",
        "category": "Countryside",
        "price_per_night": 110.00,
        "cleaning_fee": 25.00,
        "service_fee": 12.00,
        "address": "Dashashwamedh Ghat Road",
        "city": "Varanasi",
        "country": "India",
        "latitude": 25.3076,
        "longitude": 83.0104,
        "max_guests": 5,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1602216056096-3c40cc0c9944?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1598977123418-45f04b01f1bb?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Workspace"]
    },
    {
        "host_type": 1,
        "title": "Historic Haveli overlooking Golden Temple",
        "description": "Elegant luxury Haveli featuring intricate wood carvings, local fabrics, and a balcony directly overlooking the glittering Golden Temple complex.",
        "category": "Trending",
        "price_per_night": 150.00,
        "cleaning_fee": 35.00,
        "service_fee": 18.00,
        "address": "Golden Temple Outskirts",
        "city": "Amritsar",
        "country": "India",
        "latitude": 31.6200,
        "longitude": 74.8765,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1590050752117-238cb0612b1b?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Ganges-View Yoga Villa in Rishikesh",
        "description": "Serene retreat nestled in the Himalayan foothills. Offers a private yoga deck overlooking the emerald Ganges river and sound healing classes.",
        "category": "Countryside",
        "price_per_night": 125.00,
        "cleaning_fee": 30.00,
        "service_fee": 15.00,
        "address": "Laxman Jhula Marg",
        "city": "Rishikesh",
        "country": "India",
        "latitude": 30.1264,
        "longitude": 78.3242,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Hot tub", "Free parking"]
    },
    {
        "host_type": 1,
        "title": "Traditional Heritage Stay in Hampi Ruins",
        "description": "Authentic stone courtyard home nestled among the dramatic boulders and ancient temple structures of the Virupaksha ruins.",
        "category": "Countryside",
        "price_per_night": 85.00,
        "cleaning_fee": 20.00,
        "service_fee": 10.00,
        "address": "Hampi Bazaar",
        "city": "Hampi",
        "country": "India",
        "latitude": 15.3350,
        "longitude": 76.4600,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Traditional Villa near Meenakshi Temple",
        "description": "Spacious Chettinad-style villa with open courtyards, pillars, and antique tiles, located minutes away from Madurai Meenakshi Amman Temple.",
        "category": "Trending",
        "price_per_night": 105.00,
        "cleaning_fee": 25.00,
        "service_fee": 12.00,
        "address": "East Chitrai Street",
        "city": "Madurai",
        "country": "India",
        "latitude": 9.9195,
        "longitude": 78.1193,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "images": [
            "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Free parking", "TV"]
    },

    # --- NEW ZEALAND ---
    {
        "host_type": 1,
        "title": "Architectural Alpine Lodge in Queenstown",
        "description": "High-end luxury cabin perched above Lake Wakatipu. Features an architectural glass facade, outdoor hot tub, fireplace, and sweeping snow views.",
        "category": "Cabins",
        "price_per_night": 450.00,
        "cleaning_fee": 100.00,
        "service_fee": 50.00,
        "address": "Crown Range Road",
        "city": "Queenstown",
        "country": "New Zealand",
        "latitude": -44.9801,
        "longitude": 168.8504,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Hot tub", "Heating", "Free parking", "Gym"]
    },
    {
        "host_type": 2,
        "title": "Rotorua Geothermal Eco-Cabin",
        "description": "Eco-friendly wooden cabin nestled amidst native ferns. Features natural geothermally-heated hot tub and private lakeside walkway.",
        "category": "Lakefront",
        "price_per_night": 220.00,
        "cleaning_fee": 60.00,
        "service_fee": 30.00,
        "address": "Lake Tarawera Road",
        "city": "Rotorua",
        "country": "New Zealand",
        "latitude": -38.1368,
        "longitude": 176.2497,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Hot tub", "Heating", "Free parking"]
    },
    {
        "host_type": 1,
        "title": "Milford Sound Wilderness Escape",
        "description": "Off-grid secluded cabin located in the rainforests of Fiordland. Access to hiking trails, roaring fireplace, and mountain rivers.",
        "category": "Countryside",
        "price_per_night": 260.00,
        "cleaning_fee": 70.00,
        "service_fee": 35.00,
        "address": "Milford Sound Highway",
        "city": "Fiordland",
        "country": "New Zealand",
        "latitude": -44.6716,
        "longitude": 167.9254,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["Kitchen", "Heating", "Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Auckland Waterfront Penthouse",
        "description": "Sleek, high-floor luxury apartment overlooking Waitemata Harbour. Walk to Viaduct Harbour's restaurants and enjoy skyline lights.",
        "category": "Mansions",
        "price_per_night": 390.00,
        "cleaning_fee": 110.00,
        "service_fee": 55.00,
        "address": "Quay Street",
        "city": "Auckland",
        "country": "New Zealand",
        "latitude": -36.8485,
        "longitude": 174.7633,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace", "Gym"]
    },

    # --- AUSTRALIA ---
    {
        "host_type": 1,
        "title": "Luxury Beachfront Villa on Gold Coast",
        "description": "Step directly onto the golden sands from this designer-furnished multi-million dollar beach house with private saltwater pool.",
        "category": "Beachfront",
        "price_per_night": 610.00,
        "cleaning_fee": 150.00,
        "service_fee": 75.00,
        "address": "Albatross Avenue",
        "city": "Gold Coast",
        "country": "Australia",
        "latitude": -28.0335,
        "longitude": 153.4358,
        "max_guests": 8,
        "bedrooms": 4,
        "beds": 6,
        "bathrooms": 4.0,
        "images": [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Hot tub", "Air conditioning", "Free parking", "TV"]
    },
    {
        "host_type": 2,
        "title": "Great Barrier Reef Private Island Resort",
        "description": "Ultra-exclusive island villa surrounded by coral reefs. Watch tropical sea life right from your terrace.",
        "category": "Islands",
        "price_per_night": 950.00,
        "cleaning_fee": 200.00,
        "service_fee": 120.00,
        "address": "Hamilton Island Way",
        "city": "Whitsundays",
        "country": "Australia",
        "latitude": -20.3489,
        "longitude": 148.9573,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.5,
        "images": [
            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "TV", "Gym"]
    },
    {
        "host_type": 1,
        "title": "Chic Contemporary Loft in Melbourne",
        "description": "Stylish brick-walled loft in Melbourne's iconic laneways. Complete with luxury concrete designs, espresso bar, and record player.",
        "category": "Trending",
        "price_per_night": 170.00,
        "cleaning_fee": 50.00,
        "service_fee": 25.00,
        "address": "Hosier Lane",
        "city": "Melbourne",
        "country": "Australia",
        "latitude": -37.8164,
        "longitude": 144.9691,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Byron Bay Rainforest Sanctuary",
        "description": "Eco-designed glass house surrounded by ancient eucalyptus trees. Enjoy outdoor rain showers and deck vistas.",
        "category": "Cabins",
        "price_per_night": 290.00,
        "cleaning_fee": 80.00,
        "service_fee": 40.00,
        "address": "Rainforest Road",
        "city": "Byron Bay",
        "country": "Australia",
        "latitude": -28.6474,
        "longitude": 153.6120,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Hot tub", "Free parking", "Washer"]
    },

    # --- OTHER GLOBAL DESTINATIONS ---
    {
        "host_type": 1,
        "title": "Traditional Machiya Townhouse in Kyoto",
        "description": "Authentic wooden townhouse with Tatami mats, private Zen garden, sliding shoji screens, and a cypress wood soaking tub.",
        "category": "Countryside",
        "price_per_night": 230.00,
        "cleaning_fee": 60.00,
        "service_fee": 30.00,
        "address": "Gion-machi South Side",
        "city": "Kyoto",
        "country": "Japan",
        "latitude": 35.0037,
        "longitude": 135.7782,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "Hot tub", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Private Pool Villa in Ubud Jungle",
        "description": "Wake up above the jungle canopy in Ubud. This design-forward tropical villa features a large infinity pool and private chef service.",
        "category": "Islands",
        "price_per_night": 310.00,
        "cleaning_fee": 80.00,
        "service_fee": 40.00,
        "address": "Sayan Ridge",
        "city": "Bali",
        "country": "Indonesia",
        "latitude": -8.5069,
        "longitude": 115.2625,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "Free parking", "Gym"]
    },
    {
        "host_type": 1,
        "title": "Overwater Bungalow in Bora Bora",
        "description": "Unrivalled luxury hovering over the turquoise waters of Bora Bora. Features a private plunge pool and glass floor panels.",
        "category": "Islands",
        "price_per_night": 1200.00,
        "cleaning_fee": 250.00,
        "service_fee": 150.00,
        "address": "Motu Piti Aau",
        "city": "Bora Bora",
        "country": "French Polynesia",
        "latitude": -16.5004,
        "longitude": -151.7415,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "TV"]
    },
    {
        "host_type": 2,
        "title": "Charming Swiss Alps Ski Chalet",
        "description": "Traditional wooden chalet located at the base of the Matterhorn. Offers ski-in/ski-out convenience, a dry sauna, and fireplace.",
        "category": "Cabins",
        "price_per_night": 480.00,
        "cleaning_fee": 120.00,
        "service_fee": 60.00,
        "address": "Winkelmatten Road",
        "city": "Zermatt",
        "country": "Switzerland",
        "latitude": 46.0207,
        "longitude": 7.7491,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "images": [
            "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "Hot tub", "Workspace", "Washer"]
    },
    {
        "host_type": 1,
        "title": "Clifftop Cave House in Amalfi Coast",
        "description": "Dramatic clifftop home in Positano. Hand-painted ceramic tiles, high ceilings, and a private terraced garden looking onto the sea.",
        "category": "Beachfront",
        "price_per_night": 550.00,
        "cleaning_fee": 130.00,
        "service_fee": 70.00,
        "address": "Via Cristoforo Colombo",
        "city": "Positano",
        "country": "Italy",
        "latitude": 40.6281,
        "longitude": 14.4850,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Historic Canal-Front Palazzo in Venice",
        "description": "Step back in time inside this 16th-century Venetian palazzo. High ceilings, original frescoes, and a private water-gate balcony.",
        "category": "Lakefront",
        "price_per_night": 420.00,
        "cleaning_fee": 110.00,
        "service_fee": 55.00,
        "address": "Calle del Dose",
        "city": "Venice",
        "country": "Italy",
        "latitude": 45.4344,
        "longitude": 12.3388,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1519677100203-a0e6d5379409?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Heating", "TV"]
    },
    {
        "host_type": 1,
        "title": "Luxury Safari Tent in Serengeti",
        "description": "Glamping inside the Serengeti National Park. Offers luxury canvas design, private solar hot tub, and daily wildlife drives.",
        "category": "Desert",
        "price_per_night": 650.00,
        "cleaning_fee": 100.00,
        "service_fee": 60.00,
        "address": "Central Serengeti Campsite",
        "city": "Serengeti",
        "country": "Tanzania",
        "latitude": -2.1540,
        "longitude": 34.6857,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["Hot tub", "Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Sleek Modern Penthouse in New York City",
        "description": "Stunning loft apartment in Soho featuring double-height ceiling windows, concrete details, and a rooftop overlooking Manhattan.",
        "category": "Mansions",
        "price_per_night": 720.00,
        "cleaning_fee": 180.00,
        "service_fee": 90.00,
        "address": "Greene Street",
        "city": "New York",
        "country": "United States",
        "latitude": 40.7246,
        "longitude": -74.0018,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.5,
        "images": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1496568818309-53d7c7753022?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace", "Gym"]
    },
    {
        "host_type": 1,
        "title": "Volcanic Cave Dome in Iceland",
        "description": "Architectural glass dome situated Vik. Enjoy the northern lights right from your bed.",
        "category": "Countryside",
        "price_per_night": 290.00,
        "cleaning_fee": 80.00,
        "service_fee": 40.00,
        "address": "Black Sand Dunes Road",
        "city": "Vik",
        "country": "Iceland",
        "latitude": 63.4194,
        "longitude": -19.0060,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "Free parking"]
    },
    {
        "host_type": 2,
        "title": "Cappadocia Cave Suites & Balloon View",
        "description": "Charming stone suite carved inside Cappadocia's ancient volcanic formations. Enjoy sunrise balloon views from the terrace.",
        "category": "Trending",
        "price_per_night": 195.00,
        "cleaning_fee": 50.00,
        "service_fee": 25.00,
        "address": "Aydinli Street",
        "city": "Göreme",
        "country": "Turkey",
        "latitude": 38.6431,
        "longitude": 34.8289,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "TV", "Free parking"]
    },
    {
        "host_type": 1,
        "title": "Luxurious Desert Campsite in Sahara",
        "description": "Glamping inside a luxury hand-woven Berber tent. Complete with authentic Moroccan rugs and private solar shower.",
        "category": "Desert",
        "price_per_night": 210.00,
        "cleaning_fee": 50.00,
        "service_fee": 25.00,
        "address": "Erg Chebbi Dunes",
        "city": "Merzouga",
        "country": "Morocco",
        "latitude": 31.0983,
        "longitude": -4.0033,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Chic Parisian Apartment near Eiffel Tower",
        "description": "Elegantly styled Haussmannian apartment Classic French balcony offering view of the Eiffel Tower.",
        "category": "Mansions",
        "price_per_night": 320.00,
        "cleaning_fee": 80.00,
        "service_fee": 40.00,
        "address": "Avenue Rapp",
        "city": "Paris",
        "country": "France",
        "latitude": 48.8584,
        "longitude": 2.2945,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.0,
        "images": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1502014822147-1aedfb067b78?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Heating", "TV", "Workspace"]
    },
    {
        "host_type": 1,
        "title": "Modern Oceanfront Villa in Cape Town",
        "description": "Watch waves crash against the Clifton shoreline. Oceanfront infinity pool and glass elevators.",
        "category": "Beachfront",
        "price_per_night": 790.00,
        "cleaning_fee": 160.00,
        "service_fee": 90.00,
        "address": "Victoria Road, Clifton",
        "city": "Cape Town",
        "country": "South Africa",
        "latitude": -33.9378,
        "longitude": 18.3785,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.5,
        "images": [
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Hot tub", "Air conditioning", "Free parking", "Gym"]
    },
    {
        "host_type": 2,
        "title": "Panoramic Lagoon Pool House in Phuket",
        "description": "Stunning designer pool villa located along Phuket. Steps away from the sand.",
        "category": "Islands",
        "price_per_night": 380.00,
        "cleaning_fee": 90.00,
        "service_fee": 45.00,
        "address": "Bangtao Beach Road",
        "city": "Phuket",
        "country": "Thailand",
        "latitude": 7.9840,
        "longitude": 98.2920,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "images": [
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "Free parking", "TV"]
    },
    {
        "host_type": 1,
        "title": "Rustic Log Cabin in Banff National Park",
        "description": "Traditional Canadian log cabin surrounded by mountain pines. Outdoor wood-fired hot tub and alpine views.",
        "category": "Cabins",
        "price_per_night": 295.00,
        "cleaning_fee": 80.00,
        "service_fee": 40.00,
        "address": "Mountain Avenue",
        "city": "Banff",
        "country": "Canada",
        "latitude": 51.1784,
        "longitude": -115.5708,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Hot tub", "Heating", "Free parking", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Tropical Beachfront Bungalow in Costa Rica",
        "description": "Secluded beachfront wooden bungalow. Walk onto the sand and enjoy ocean breezes.",
        "category": "Beachfront",
        "price_per_night": 240.00,
        "cleaning_fee": 60.00,
        "service_fee": 30.00,
        "address": "Playa Manuel Antonio",
        "city": "Manuel Antonio",
        "country": "Costa Rica",
        "latitude": 9.3874,
        "longitude": -84.1481,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1500964757637-c85e8a162699?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Air conditioning", "Free parking", "Washer"]
    },
    {
        "host_type": 1,
        "title": "Private Island Villa in Maldives",
        "description": "Luxury overwater villa overlooking lagoons. Enjoy infinity pool and direct ocean access.",
        "category": "Islands",
        "price_per_night": 1400.00,
        "cleaning_fee": 250.00,
        "service_fee": 180.00,
        "address": "Dhigufinolhu Island",
        "city": "Male",
        "country": "Maldives",
        "latitude": 4.1755,
        "longitude": 73.5093,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1.5,
        "images": [
            "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "TV", "Workspace"]
    },
    {
        "host_type": 2,
        "title": "Stately Georgian Townhouse in London",
        "description": "Georgian townhouse in Chelsea. Classical elegance meets premium contemporary finishes.",
        "category": "Mansions",
        "price_per_night": 460.00,
        "cleaning_fee": 120.00,
        "service_fee": 60.00,
        "address": "King's Road",
        "city": "London",
        "country": "United Kingdom",
        "latitude": 51.4875,
        "longitude": -0.1685,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3.0,
        "images": [
            "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Heating", "TV", "Workspace", "Washer"]
    },
    {
        "host_type": 1,
        "title": "Red Rock Desert Retreat in Sedona",
        "description": "Stunning luxury home with vistas of Sedona's red rocks.",
        "category": "Desert",
        "price_per_night": 395.00,
        "cleaning_fee": 100.00,
        "service_fee": 50.00,
        "address": "Red Rock Loop Road",
        "city": "Sedona",
        "country": "United States",
        "latitude": 34.8697,
        "longitude": -111.7601,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2.0,
        "images": [
            "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800",
            "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&q=80&w=800"
        ],
        "amenities": ["WiFi", "Kitchen", "Pool", "Air conditioning", "Free parking", "TV"]
    }
]
